cargo: Enable LTO on release build
hickory-dns/hickory-dns pull request #2141
Opened 2024-02-09 13:59 UTC by jpds

2024-02-11 17:42 UTC, bluejekyll commented
I think I fixed the cleanliness issues. In terms of LTO, I used to see some issues with it functioning properly. Can you do us a favor, and list out the reasons for wanting it enabled? It would also be great to show before and after binary sizes to show the value here.

2024-03-12 09:15 UTC, djc approved these changes

2024-03-16 16:34 UTC, bluejekyll commented
Thank you, I appreciate the follow up. Will merge, and thanks for the PR!

2024-03-16 16:39 UTC, bluejekyll commented on Cargo.toml
> +opt-level = "s"
Do we want `s` or `3` here? I'm a little uncomfortable with optimizing for size, when I think we in most cases want to optimize for speed.

2024-03-16 16:48 UTC, bluejekyll commented on Cargo.toml
> +strip = true
I'd prefer this to be `symbols` to be clearer which strip mode is being enabled.

2024-05-18 19:17 UTC, bluejekyll requested changes
see above comments for changes requested.

2024-05-19 14:29 UTC, bluejekyll approved these changes

2024-05-19 14:30 UTC, bluejekyll commented
Thank you for following up and the PR.

2024-05-19 14:30 UTC, merged