⌛ Lower the default timeout for dns resolves
hickory-dns/hickory-dns pull request #2227
Opened 2024-05-30 13:31 UTC by Jasper-Bekkers

Partially addresses #2225 

I think it would be good to have more control over this ultimately, specifically in the `from_system_conf` case, but for now this addresses my needs at least.

2024-05-30 13:49 UTC, djc approved these changes

2024-05-30 13:49 UTC, djc commented
Thanks!

2024-05-30 18:31 UTC, bluejekyll commented
100ms is pretty aggressive, when pinging a system across a continent, > 100ms is quite common for latency of those requests.

2024-06-02 20:56 UTC, bluejekyll requested changes

2024-06-02 20:56 UTC, bluejekyll commented on crates/resolver/src/config.rs
> +            timeout: Duration::from_millis(100),
I don't think this is a reasonable general timeout base on my previous comment, real world latencies. I think I'd be ok with this being lowered to 2 seconds, but 100ms is too aggressive IMO.

2024-06-17 19:12 UTC, bluejekyll commented
@Jasper-Bekkers, just pinging you on this about how we should proceed here?

2024-06-17 19:42 UTC, Jasper-Bekkers commented
I have a workaround in place now. Though I think somebody with more knowledge of these systems should expose the default timeout value in a way that can be changed from code. That would make this issue disappear in the correct way.

2024-08-31 22:32 UTC, bluejekyll commented
Closing this, I think we should open an issue to revisit.

2024-08-31 22:32 UTC, closed without merging