Add test to check cache hit with DO bit
hickory-dns/hickory-dns pull request #2280
Opened 2024-07-03 14:18 UTC by justahero

This adds the companion test to check that a previously cached request with DO bit set to `0` followed by a second request with DO bit set to `1` returns all DNSSEC records, answer + RRSIG, hitting the cache.

2024-07-03 15:31 UTC, pvdrz approved these changes

2024-07-03 15:32 UTC, pvdrz commented
I'd add some extra comments explaining each dig command but I don't think it is a blocker

2024-07-03 16:56 UTC, japaric requested changes
this test should check the caching behavior

2024-07-03 16:56 UTC, japaric commented on conformance/packages/conformance-tests/src/resolver/dnssec/rfc4035/section_3/section_3_2.rs
> +    let ans = client.dig(settings, resolver_addr, RecordType::SOA, &FQDN::ROOT)?;
this is meant to be a test of the caching behavior (+) so it should check that no network communication with the nameservers happens on the second query using the `eavesdrop` API. see #2244 for an example of that.

the current assertions should be preserved.

 (+) for that reason, I would also put this test inside module `section_4_5` which is created in #2244

2024-07-04 11:23 UTC, japaric approved these changes
thank you

2024-07-04 11:40 UTC, japaric commented
> https://github.com/hickory-dns/hickory-dns/actions/runs/9793429806/job/27041346942?pr=2280#step:10:43

a clippy lint needs to be fixed

2024-07-04 12:53 UTC, merged