conformance: zone that lacks DS in parent zone
hickory-dns/hickory-dns pull request #2388
Opened 2024-08-27 11:05 UTC by japaric

port of `no-ds` from EDE dot com

like #2380 this is another "Insecure" scenario where hickory is answering with SERVFAIL instead of NOERROR+ad=false

2024-09-01 00:40 UTC, bluejekyll requested changes
Just want a little more info on a comment, otherwise looks fine to me.

2024-09-01 00:40 UTC, bluejekyll commented on conformance/packages/conformance-tests/src/resolver/dnssec/scenarios/insecure.rs
> +    // tld_ns.add(no_ds_ns.ds().clone()); // IMPORTANT omit this!
Can you update the comment as to why?

2024-09-02 16:09 UTC, japaric commented
updated to actually sign the `no_ds` zone and to not use variables like `nameservers_ns` (see #2408 )

2024-09-13 08:24 UTC, japaric commented
@bluejekyll reminder that this PR cannot be merged until you update your review

2024-10-12 15:49 UTC, marcus0x62 approved these changes

2024-10-15 12:10 UTC, japaric commented
> @bluejekyll reminder that this PR cannot be merged until you update your review

@bluejekyll ping ^

2024-10-29 14:35 UTC, justahero approved these changes

2024-10-29 16:09 UTC, japaric commented
is `e2e_tests::tx_id_validation_test` known to spuriously fail? the test is not modified by this PR and this PR does not modify hickory-dns code either. I cannot repro the failure locally after running `just e2e-tests` dozens of times. cc @marcus0x62 

[from this build job](https://github.com/hickory-dns/hickory-dns/actions/runs/11577413801/job/32228737228?pr=2388#step:10:461):

``` console
failures:

---- recursor::security::scenarios::tx_id_validation_test stdout ----
STDOUT:
;; communications error to 192.168.160.4#53: timed out
;; communications error to 192.168.160.4#53: timed out
;; communications error to 192.168.160.4#53: timed out

; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> +recurse +nodnssec +adflag +nocdflag @192.168.160.4 A www.example.testing.
; (1 server found)
;; global options: +cmd
;; no servers could be reached
STDERR:

thread 'recursor::security::scenarios::tx_id_validation_test' panicked at src/recursor/security/scenarios.rs:55:9:
error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2024-10-29 16:39 UTC, merged

2024-10-29 18:41 UTC, marcus0x62 commented
> is `e2e_tests::tx_id_validation_test` known to spuriously fail? the test is not modified by this PR and this PR does not modify hickory-dns code either. I cannot repro the failure locally after running `just e2e-tests` dozens of times. cc @marcus0x62
> 
> [from this build job](https://github.com/hickory-dns/hickory-dns/actions/runs/11577413801/job/32228737228?pr=2388#step:10:461):
> 
> ```
> failures:
> 
> ---- recursor::security::scenarios::tx_id_validation_test stdout ----
> STDOUT:
> ;; communications error to 192.168.160.4#53: timed out
> ;; communications error to 192.168.160.4#53: timed out
> ;; communications error to 192.168.160.4#53: timed out
> 
> ; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> +recurse +nodnssec +adflag +nocdflag @192.168.160.4 A www.example.testing.
> ; (1 server found)
> ;; global options: +cmd
> ;; no servers could be reached
> STDERR:
> 
> thread 'recursor::security::scenarios::tx_id_validation_test' panicked at src/recursor/security/scenarios.rs:55:9:
> error
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

I haven't seen failures with that test so far, and while it does use some new features I added to the conformance suite (the leaf resolver in that test is a python script,) that error looks like a problem with the client being unable to communicate with the resolver and none of that should be unusual or unique...