Fix udp create immediate polling wrong
hickory-dns/hickory-dns pull request #2462
Opened 2024-09-16 16:50 UTC by mokeyish

This PR fixes that `self.closure` is not immediately ready.

2024-09-16 17:38 UTC, bluejekyll requested changes
minor change to add some documentation, otherwise, this looks like a really good change. Thank you.

2024-09-16 17:38 UTC, bluejekyll commented on crates/proto/src/udp/udp_stream.rs
> +    state: Option<(usize, UdpSocketCreateFuture<S>)>,
need some documentation here that the `usize` is the number of attempted socket creation attempts.

2024-09-16 17:38 UTC, bluejekyll commented on crates/proto/src/udp/udp_stream.rs
> +    state: Option<(usize, UdpSocketCreateFuture<S>)>,
alternatively, this could be a named type that is just an alias to `usize` to make it self-documenting.

2024-09-17 10:25 UTC, djc commented
See previous PR:

- https://github.com/hickory-dns/hickory-dns/pull/2157

2024-09-18 08:06 UTC, djc commented
(See alternative in #2464.)

2024-09-18 17:35 UTC, bluejekyll commented
@djc, this patch looks more correct to me. then that previous patch. @mokeyish, I'm assuming this is patching an issue that's been seen in the wild, can you describe that scenario?

2024-09-25 08:19 UTC, djc commented
Closing, since we merged #2464.

2024-09-25 08:19 UTC, closed without merging