hickory-proto(serde): fix transparent structs and allow (de)serializing more types.
hickory-dns/hickory-dns pull request #2544
Opened 2024-11-01 10:31 UTC by ArjixWasTaken

2024-11-01 10:53 UTC, ArjixWasTaken commented
Sorry for the force pushes, I wanted the commit diffs to be as minimal as possible.
Sadly my vscode diff view did not pick up on whitespace changes, so I had to manually find them and fix them after the commits were already made.

2024-11-01 12:07 UTC, marcus0x62 commented
> Sorry for the force pushes, I wanted the commit diffs to be as minimal as possible.
> 
> Sadly my vscode diff view did not pick up on whitespace changes, so I had to manually find them and fix them after the commits were already made.

The force pushes are fine, but you do have minor some formatting issues to fix. (see the output for the cleanliness test.)  Anything that throws a rust fmt error will not pass CI.

Don't worry about the conformance teat failure for now - it doesn't have anything to do with your PR.  I'll fix that, then you'll need to rebase your commits.

2024-11-01 12:15 UTC, ArjixWasTaken commented
how is the cleanliness measured?
it doesn't complain about the rest of the file, even though it should according to rust fmt

does it only complain about new code?

2024-11-01 14:41 UTC, marcus0x62 requested changes
Overall, this looks good.  Prior to merging we'll need:

1) to fix the remaining formatting issues:

```
cargo ws exec cargo fmt -- --check
Diff in /home/runner/work/hickory-dns/hickory-dns/crates/proto/src/op/edns.rs:10:
 use std::fmt;
 
 #[cfg(feature = "serde")]
-use serde::{ Deserialize, Serialize };
+use serde::{Deserialize, Serialize};
 
 #[cfg(feature = "dnssec")]
 use crate::rr::dnssec::{Algorithm, SupportedAlgorithms};
Diff in /home/runner/work/hickory-dns/hickory-dns/crates/proto/src/op/header.rs:10:
 use std::{convert::From, fmt};
 
 #[cfg(feature = "serde")]
-use serde::{ Deserialize, Serialize };
+use serde::{Deserialize, Serialize};
 
 use crate::{
     error::*,
error: child command failed to exit successfully
error: Recipe `fmt` failed on line 93 with exit code 1
Error: Process completed with exit code 1.
```

2) To squash the formatting commits into the commit(s) where the original changes were introduced.

2024-11-01 15:20 UTC, ArjixWasTaken commented
I found some issues on prod (where I am directly using this) with deserialization.

I'll make this a draft when I'm back home.

SVCB params don't deserialize for the Unknown variant

2024-11-04 08:44 UTC, ArjixWasTaken commented on crates/proto/src/op/header.rs
> +#[cfg_attr(feature = "serde", derive(Deserialize, Serialize))]
interesting detail

2024-11-04 12:09 UTC, ArjixWasTaken commented
Whilst we are on the topic, I think aliasing `Record::name_labels` to `name` when serialized makes sense.
`Name` has a custom serializer, and it is converted to a string, it is not serialized as a complex structure like an array of labels.

![image](https://github.com/user-attachments/assets/e045c15c-b326-49c0-bbb6-f0a278e9f45a)

(it should be backwards compatible according to serde's documentation)

2024-11-05 09:37 UTC, djc commented on crates/proto/src/op/edns.rs
> +#[cfg_attr(feature = "serde", derive(Deserialize, Serialize))]
See https://github.com/hickory-dns/hickory-dns/pull/2549.

2025-04-18 10:54 UTC, ArjixWasTaken commented
Closing this for now.
Will re-open this PR once I am satisfied with it.

2025-04-18 10:54 UTC, closed without merging