Add case randomization config option to resolver and recursor
hickory-dns/hickory-dns pull request #2683
Opened 2024-12-17 17:39 UTC by divergentdave

This implements #2390. I tried enabling this alongside DNSSEC validation and ran into signature validation failures, so this still needs some work.

2024-12-18 20:51 UTC, marcus0x62 requested changes
Overall, this looks really good. A couple of things:

1) This is returning the case-randomized query name to the client.  We should return the original query name to the user.  I'm not aware of other implementations (Google, Unbound) doing this, and I could see it causing problems with some DNS client implementations.

2) We need some kind of fallback mechanism for the specific case where a server returns an otherwise valid message but does not maintain the randomized query case. In both the Vixie paper and google's statements about running query case randomization in production, it was observed that a small number of DNS server implementations do not correctly handle randomized query names.  Google maintains a private list of offending servers and doesn't randomize queries to those.  Other approaches that have been described are to set an error threshold for individual name servers and to stop sending randomized query names after *n* failures, or to fall back to TCP.  Unbound allows users to explicitly configure a list of networks and domains to bypass case randomization for, but I don't think that is viable as the only fallback mechanism for this.

2024-12-20 00:25 UTC, divergentdave commented
>     1. This is returning the case-randomized query name to the client.  We should return the original query name to the user.  I'm not aware of other implementations (Google, Unbound) returning the randomized query name, and I could see it causing problems with some DNS client implementations.

FWIW the catalog is using its unchanged copy of the query when building responses to be sent by the server: https://github.com/hickory-dns/hickory-dns/blob/5ec78723506a559761586281824fa56d0efb89a5/crates/server/src/authority/catalog.rs#L466 We could have `UdpClientStream` save and restore the original query at a lower layer as well, to avoid issues in other use cases.

Note however that different authoritative servers may reflect randomized name cases differently elsewhere in their responses. Depending on which peer implementation I use in conformance tests, I'm seeing either lowercase or mixed case names in answer section record names and NS record data. This is probably because of differences in case sensitivity in how they each implement label compression.

>     2. We need some kind of fallback mechanism for the specific case where a server returns an otherwise valid message but does not maintain the randomized query case. In both the Vixie paper and google's statements about running query case randomization in production, it was observed that a small number of DNS server implementations do not correctly handle randomized query names.  Google maintains a private list of offending servers and doesn't randomize queries to those.  Other approaches that have been described are to set an error threshold for individual name servers and to stop sending randomized query names after _n_ failures, or to fall back to TCP.  Unbound allows users to explicitly configure a list of networks and domains to bypass case randomization for, but I don't think that is viable as the only fallback mechanism for this.

Falling back to TCP definitely makes sense, I'll add a test for that for starters.

2025-01-10 09:29 UTC, djc commented
(@divergentdave in case you're waiting for me, I'd prefer to review after this is rebased on main.)

2025-01-10 19:18 UTC, djc approved these changes
LGTM!

2025-01-10 19:18 UTC, djc commented on crates/proto/src/op/query.rs
> +        let Query {
This stuff makes me wonder if it really makes sense to have both `Query` and `QueryParts`? Maybe we should just make `Query`'s fields public (maybe stick a `#[non_exhaustive]` on it) and ditch `QueryParts`?

2025-01-10 19:18 UTC, djc commented on crates/proto/src/error.rs
> +    pub fn is_query_case_mismatch(&self) -> bool {
Hmm, this seems pretty low-value to me, can we just inline it?

2025-01-10 19:18 UTC, djc commented on crates/proto/src/udp/udp_client_stream.rs
> +        let serial_message = SerialMessage::new(bytes, self.name_server);
Nit: so this should no longer be necessary, and `serial_message` feels kinda verbose/overkill for this.

2025-01-10 19:18 UTC, djc commented on crates/proto/src/udp/udp_client_stream.rs
> +    original_query: &Option<Query>,
Nit: `&Option<Query>` is a little unidiomatic, use `Option<&Query>` instead?

2025-01-10 19:18 UTC, djc commented on crates/proto/src/xfer/dns_handle.rs
> +        self.send(build_request(query, options))
I'd prefer for this kind of thing to be in a different commit, since this one is large enough already. Also maybe `build_request()` should be a constructor on `DnsRequest` instead?

2025-01-10 19:18 UTC, djc commented on crates/recursor/src/recursor.rs
> +    /// Sets whether to randomize the case of letters in query names, and require that repsonses
For rustdoc it's usually better to have a single sentence that fits on a line. Then an empty line after that, then all the additional detail.

Also, "repsonses" is probably not what you meant.

2025-01-10 19:18 UTC, djc commented on crates/resolver/src/config.rs
> +    /// Randomize the case of letters in query names, and require that responses preserve the case
Nit: same stuff about the docstring.

2025-01-10 19:18 UTC, djc commented on crates/server/src/store/recursor/config.rs
> +    /// Randomize the case of letters in query names, and require that responses preserve the case
Nit: and here.

2025-01-20 00:06 UTC, bluejekyll commented
@djc, I see your last statement is LGTM, but then a few unresolved change requests. @divergentdave, did you get those?

2025-01-20 09:27 UTC, djc commented
> @djc, I see your last statement is LGTM, but then a few unresolved change requests. @divergentdave, did you get those?

Since @divergentdave pushed after my review, I assume he resolved those. @divergentdave if so, feel free to go ahead and merge, since I have approved (unless you wanted to get a round of review from someone else). Also would be nice if you can "Resolve" the comments that you're reasonably sure you addressed.

2025-01-21 21:49 UTC, divergentdave commented on crates/proto/src/xfer/dns_handle.rs
> +        self.send(build_request(query, options))
I think I'd prefer to keep `build_request()` in this file for the time being, in order to keep the comment about randomizing the ID near the poll method it references.

2025-01-21 22:00 UTC, divergentdave commented on crates/proto/src/op/query.rs
> +        let Query {
Looking back at the history, #1397 introduced `QueryParts` in order to destructure a `Query` and use its buffers without copying them to new allocations. All four setter methods on `Query` don't do any validation, so the type isn't maintaining any invariants. I think making the fields public makes sense, how about I do so in a follow-up PR?

2025-01-21 22:09 UTC, divergentdave commented
Pinging @marcus0x62 -- could you do another review pass? This is currently blocked on your "changes requested" review.

The response now has its question section overwritten with the new `original_query` value that is passed around, and this is tested via packet capture in a conformance test. `NameServerPool` now falls back to TCP on case mismatch, and this is tested in an e2e-test.

2025-02-13 17:09 UTC, divergentdave commented
I rebased on main and fixed some conflicts

cc @marcus0x62

2025-03-02 21:26 UTC, bluejekyll commented
would be nice to land this, for some reason it says it's still out of sync?

2025-03-02 21:28 UTC, bluejekyll commented
@djc, you good with this?

2025-03-02 21:28 UTC, divergentdave commented
I just rebased it, there were no conflicts

2025-03-02 21:34 UTC, djc commented
I already approved this, but since @marcus0x62 had thoughts on it before thought it might be prudent to wait for his review. Agree that it makes sense to just merge this, and we can address any feedback from Marcus after merge.

2025-03-02 22:43 UTC, merged